%YAML 1.2
---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

ignore: |
  node_modules/**

rules:
  line-length:
    max: 100
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
  comments:
    min-spaces-from-content: 1
  document-start: disable
